# Generated by Django 2.0.5 on 2018-12-11 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manageuser',
            name='userType',
            field=models.CharField(default='Student', max_length=20),
        ),
    ]
