# Generated by Django 2.0.5 on 2018-12-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_manageuser_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='cname',
            field=models.ForeignKey(on_delete='Cascade', related_name='category_name', to='basic_app.Category'),
        ),
    ]
